name: "Update Readme"
on:
  workflow_dispatch:

  release:
    types: [ published ]
    
    
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get latest release
        id: get-latest-release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          view_top: 1
      - name: Update the readme.md
        run: |
          git switch master || (git fetch --all && git checkout -b master origin/master)
          sed "s/{{release}}/${{ steps.get-latest-release.outputs.tag_name }}/g" .github/tpl/README.tpl.md >README.md

      - uses: EndBug/add-and-commit@v9
        with:
          message: "Update version to ${{ steps.get-latest-release.outputs.tag_name }}"
          branch: master
          pull: '--rebase --autostash '
          add: |
            README.md

